#!/usr/bin/env bash

if ! command -v mpc > /dev/null ; then 
    exit 1
fi

source "$XDG_CONFIG_HOME/shell/theme.sh"

function main {
    local -r current_track="$(mpc --format "%artist%:%album%:%title%" current)"
    local -r queue=$(mpc playlist)
    IFS=':' read -r state_opt random_opt repeat_opt consume_opt <<< "$(mpc status "%state%:%random%:%repeat%:%consume%")"

    local menu_input
    local line_idx=0
    if [ -n "$queue" ] ; then

        if [ "$state_opt" = "playing" ]; then 
            local -r play_line="󰏤 Pause\n"
        else 
            local -r play_line+="󰐊 Play\n"
        fi

        if [ -n "$current_track" ]; then 
            menu_input+="󰒮 Previous track\n"
            local -r prev_line_idx=$(( line_idx ))
            ((line_idx+=1))

            menu_input+="$play_line"
            local -r play_line_idx=$(( line_idx ))
            ((line_idx+=1))

            menu_input+="󰒭 Next track\n"
            local -r next_line_idx=$(( line_idx ))
            ((line_idx+=1))

        else 
            menu_input+="$play_line"
            local -r play_line_idx=$(( line_idx ))
            ((line_idx+=1))

            local -r prev_line_idx=-1 next_line_idx=-1
        fi

        menu_input+="󰲸 Current playlist\n"
        local -r playlist_line_idx=$(( line_idx ))
        ((line_idx+=1))
    else 
        local -r play_line_idx=-1 prev_line_idx=-1 next_line_idx=-1 playlist_line_idx=-1
    fi 

    menu_input+="󰑖 Repeat: $repeat_opt\n"
    local -r repeat_line_idx=$(( line_idx ))
    (( line_idx+=1 ))

    menu_input+="󰒟 Random: $random_opt\n"
    local -r random_line_idx=$(( line_idx ))
    (( line_idx+=1 ))

    menu_input+=" Consume: $consume_opt\n"
    local -r consume_line_idx=$(( line_idx ))
    (( line_idx+=1 ))

    local -r preselected_line=$( ((play_line_idx == -1)) && echo 0 || echo $play_line_idx )

    local -r variant=$(echo -en "$menu_input" | \
        dmenu -i -idx -p "󰎄 MUSIC:" \
        -n "$preselected_line" \
        -l $line_idx)

    if [ -z "$variant" ]; then 
        exit 1
    fi

    case "$variant" in 
    $(( play_line_idx )) )
        if [ "$state_opt" = "playing" ]; then 
            mpc pause
        else 
            mpc play
        fi
        ;;
    $(( playlist_line_idx )) )
        local -r MAX_PLAYLIST_LINES=15
        local -r playlist_tracks="$(mpc --format "%title% (%artist% - %album%)" playlist)"
        local -r playlist_size=$(grep -cv '^$' <<< "$playlist_tracks")
        local -r current_playlist_position=$(( $(mpc status "%songpos%") - 1 ))

        local menu_input_playlist=""
        while read -r line 
        do 
            if [ -n "$line" ]; then 
                menu_input_playlist+="󰝚 ) $line\n"
            fi
        done <<< "$playlist_tracks"

        local -r variant_track=$(echo -en "$menu_input_playlist" \
            | dmenu -i -idx -p "󰎄 PLAYLIST:" \
            -n "$current_playlist_position" \
            -l $(( playlist_size > MAX_PLAYLIST_LINES ? MAX_PLAYLIST_LINES : playlist_size ))
        )

        if [ -n "$variant_track" ]; then 
            mpc play $(( variant_track + 1 ))
        fi 
    ;;
    $(( prev_line_idx )) ) mpc prev ;;
    $(( next_line_idx )) ) mpc next ;;
    $(( repeat_line_idx )) ) mpc repeat ;;
    $(( random_line_idx )) ) mpc random ;;
    $(( consume_line_idx )) ) mpc consume ;;
    *) exit 2 ;;
    esac 
}

main "$@"
