#!/usr/bin/env bash

if ! command -v pass > /dev/null ; then 
    exit 1
fi

PASSWORDS_DIR=${PASSWORD_STORE_DIR:-$HOME/.password-store}

source "$XDG_CONFIG_HOME/shell/theme.sh"

function usb-available() {
    local mountpoint output

    for disk in $(lsblk -dn -o NAME,TRAN \
        | awk '$2=="usb" {print $1}'); do
        for part in $(lsblk -ln -o NAME,TYPE "/dev/$disk" \
            | awk '$2=="part" {print $1}'); do
            mountpoint="$(lsblk -no MOUNTPOINT "/dev/$part")"
            if [ -n "${mountpoint}" ]; then 
                output="${output}${mountpoint}\n"
            fi
        done
    done
    echo -en "$output"
}

function main() {  
    local -r MAX_PASSWORD_LINES=15
    local -r passwords=$(find "$PASSWORDS_DIR" -type f -name '*.gpg' \
        | sed -e "s|^$PASSWORDS_DIR/||" \
              -e 's|\.gpg$||' \
              -e '/^$/d')
    local -r passwords_count=$(grep -cv '^$' <<< "${passwords}")

    local menu_input 
    menu_input=" Add password\n"

    if (( passwords_count > 0 )); then 
        menu_input+=" Remove password\n"
        local -r remove_password_line=1
    fi

    if pass git status 2>/dev/null \
        && pass git remote -v 2>/dev/null | grep "origin" ; then 
        menu_input+=" Sync from git\n"
        local -r sync_git_line=1
    fi

    local -r usb_drives=$(usb-available)
    if [ -n "${usb_drives}" ] && (( passwords_count > 0 )); then 
        menu_input+="󰕓 Sync to USB\n"
        local -r sync_usb_line=1
    fi

    local menu_input_passwords=""
    if [ -n "$passwords" ]; then 
        while read -r line 
        do 
            if [ -n "$line" ]; then 
                menu_input_passwords+="  $line\n"
            fi
        done <<< "$passwords"
    fi
    menu_input+="$menu_input_passwords"
    local -r rows_count=$(( passwords_count + 1 + remove_password_line + sync_git_line + sync_usb_line ))

    local -r variant=$(echo -en "$menu_input" \
        | dmenu -i -idx -p " PASSWORDS:" \
        -l $(( rows_count > MAX_PASSWORD_LINES ? MAX_PASSWORD_LINES : rows_count  )) )

    if [ -z "$variant" ]; then
        exit;
    fi 

    local -r control_lines=$(( 1 + remove_password_line + sync_git_line + sync_usb_line  ))
    local -r idx_new=0
    local idx=1

    if (( remove_password_line )); then 
        local -r idx_remove=$(( idx ))
        (( idx += 1))
    else 
        local -r idx_remove=-1
    fi

    if (( sync_git_line )); then 
        local -r idx_git=$(( idx ))
        (( idx += 1))
    else 
        local -r idx_git=-1
    fi
    if (( sync_usb_line )); then 
        local -r idx_usb=$(( idx ))
        (( idx += 1))
    else 
        local -r idx_usb=-1
    fi

    case "$variant" in 
        $((idx_new)) )
            local -r password_service=$(dmenu -p " SERVICE:") 

            if [ -z "$password_service" ]; then  
                exit
            fi

            if pass generate "${password_service}"; then 
                notify-send -u normal -i password-manager \
                    "Password generated" \
                    "Password for ${password_service} has been successfully generated"
                if (( sync_git_line )); then
                    if ! pass git push origin master ; then 
                        notify-send -u critical -i password-manager \
                            "Password synchronization failed" \
                            "Password for ${password_service} was generated, but failed to push to remote Git repository"
                    fi
                fi 
            else 
                notify-send -u critical -i password-manager \
                    "Password generation error" \
                    "Failed to generate password for ${password_service}"
            fi
        ;;
        $((idx_remove)) )
            local -r variant_remove=$(echo -en "$menu_input_passwords" \
                | dmenu -i -idx -p " DELETE:" \
                -l $(( passwords_count > MAX_PASSWORD_LINES ? MAX_PASSWORD_LINES : passwords_count  )) )

            local -r selected_service="$(sed -n "$(( variant_remove + 1))p" <<< "$passwords")"
           
            if menu-confirm " Remove password for <b>$selected_service</b>?"; then 
                if pass rm -f "$selected_service"; then 
                    notify-send -u normal -i password-manager \
                        "Password removed" \
                        "Password for $selected_service has been removed from the store"

                    if (( sync_git_line )); then
                        if ! pass git push origin master ; then 
                            notify-send -u critical -i password-manager \
                                "Password synchronization failed" \
                                "Password for $selected_service was deleted, but failed to push to remote Git repository"
                        fi
                    fi 

                fi
            fi
        ;;
        $((idx_git)) ) 
            if pass git pull origin master ; then 
                notify-send -u normal -i password-manager \
                    "Password sync complete" \
                    "Password store has been successfully synchronized with the remote Git repository"
            else 
                notify-send -u critical -i password-manager \
                    "Password sync error" \
                    "Failed to synchronize password store with the remote Git repository"
            fi
        ;;
        $((idx_usb)) )
            local -r usb_drives_count=$(grep -cv '^$' <<< "$usb_drives")
            local menu_input_usb
            while read -r line 
            do 
                if [ -n "$line" ]; then 
                    menu_input_usb+="󰕓 ) $line\n"
                fi
            done <<< "$usb_drives"

            local -r variant_usb="$(echo -en "$menu_input_usb" \
                | dmenu -i -idx -p "  USB DRIVE:" -l "${usb_drives_count}" )"

            local -r usb_selected_mount=$(sed -n "$(( variant_usb + 1 ))p" <<< "$usb_drives")

            if rsync -av --delete "$PASSWORDS_DIR" "$usb_selected_mount/password-store/" ; then 
                notify-send -u normal -i password-manager \
                    "Password backup complete" \
                    "Password store has been backed up to USB drive $usb_selected_mount"
            else 
                notify-send -u critical -i password-manager \
                    "Password sync error" \
                    "Failed to back up password store to USB drive $usb_selected_mount"
            fi
        ;;
        *)
            local -r password_idx=$(( variant - (control_lines - 1) ))

            if (( password_idx > passwords_count )); then 
                exit 1
            fi 

            local -r selected_service="$(sed -n "${password_idx}p" <<< "$passwords")"
            local -r service_data=$(pass show "$selected_service")


            if grep -q '^otpauth://' <<< "$service_data"; then
              local -r otp_present=true
            else
              local -r otp_present=false
            fi

            if [[ $(head -n 1 <<< "$service_data") == otpauth://* ]]; then
              local -r only_otp=true
            else
              local -r only_otp=false
            fi

            function copy_password() {
                if pass -c "$selected_service"; then 
                    notify-send -u normal -i password-manager \
                        "Password copied" \
                        "Password for $selected_service has been copied to clipboard"
                fi
            }

            function copy_onetime_password() {
                if pass otp -c "$selected_service"; then 
                    notify-send -u normal -i password-manager \
                        "One-time password copied" \
                        "One-time password for $selected_service has been copied to clipboard"
                fi 
            }

            if ! $otp_present; then
                copy_password
            elif $only_otp; then
                copy_onetime_password
            else
                local -r variant_password_type=$( \
                    echo -en " Password\n󰀠 One-time password\n" \
                    | dmenu -i -idx -p " $selected_service" -l 2)

                case ${variant_password_type} in 
                0) copy_password ;;
                1) copy_onetime_password ;;
                *) exit 1 ;;
                esac 
            fi
        ;;
    esac 
}

main "$@"

